### ISSUE TITLE
Load all events, not just one project

### ISSUE THREAD

**Issue by danielbenjamins** [ABOSSBV/aboss_wordpress#2]
How do I load all events from my agency account? I don't want to display just the events of one artist, but of all the artists within my agency.

**Comment by thomasvbeek** [comment]
Fixed in commit 68dcca93a5dd45f50760b54b01f808afd94cd5e8:

> To add ABOSS events from your all your agency projects (ABOSS Agency only), use:
> [aboss-events title="All Artists" display_ticket_links="yes"]
