### ISSUE TITLE
The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.

### ISSUE THREAD

**Issue by larsmtaprod** [ABOSSBV/aboss_wordpress#5]
I deactivated all plugins and changed my theme to default 2021.
When I activate ABOSS plugin I get: 
"The site is experiencing technical difficulties. Please check your site admin email inbox for instructions."
That's when the site crashes.

Any thoughts on this?
/Lars

**Comment by larsmtaprod** [comment]
I'm  using Wordpress 6.1.1 & php 8.1

**Comment by Cremz** [comment]
Hi Lars,
We will look into this, thanks for the info.

**Comment by larsmtaprod** [comment]
Hi,
This issue is still not solved.
It’s been a few months now with no solution.
Our artists still can’t add their dates to their Wordpress sites.
I’m thinking of dropping Aboss to another company.
I´m not happy!!!

Mvh,
Lars Sköld
MTA Production
Hilda Music Theatre Art Production AB
Gamla Brogatan 23a
111 20 Stockholm

Kontor: +46-(0) 8 - 660 80 88
Mobil: +46-(0) 73 83 09 666
***@***.***
www.mtaprod.se
www.facebook.com/mtaproduction

**Comment by Cremz** [comment]
@larsmtaprod We have a new version which solves the issue. Please use the new zip file for this repository.

**Comment by larsmtaprod** [comment]
3 years later, still the same problem...
